php:
    image: akhyarmaulana/pangeran-php7-mysql5.6
    ports:
        - "80:80"
    links:
        - db
        - redis
    volumes:
        - ./:/var/www/html/
db:
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: apple
    volumes:
        - ./mysql_directory:/var/lib/mysql
redis:
    image: redis
    ports: 
        - "6379:6379"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8888:80"
    links:
        - db
